### ISSUE TITLE
Accidental writing over internal IP

### ISSUE THREAD

**Issue by nikmayr** [SalvoVirga/iiwa_stack#40]
Hello,

I am using KUKA LBR 14 R800, with Sunrise 1.8. I open this issue because while following the sunrise_project_setup tutorial, I accidentally installed the sunrise project using an IP that interferes with the cabinet's internal structure. The IP I used is one within the prohibited range, as stated in the KUKA Sunrise user manual (unfortunately, I saw that after uploading). 

As a result, the cabinet Application Server fails to connect, and tries to reconnect continuously. I would like to ask whether someone faced this problem and was able to recover from that. I am considering reinstalling the Cabinet OS (any tutorials for that are welcome). 

Thank you very much!

**Comment by SalvoVirga** [comment]
Hi,

Correct me if I'm wrong, you set an IP within StationSetup > Configuration to something not allowed, so in here:

![screen_ip](https://cloud.githubusercontent.com/assets/2053024/21016006/5db82ab0-bd64-11e6-8942-d445c3c36655.png)

I don't remember in 1.8, but certainly since 1.9 you are not allowed to install a project with a setup that uses the not allowed subnet. Again, an assumption, but probably you set the IP to something in 192.168.0.xxx. This is what attempting to install should result in:

![screen_ip_2](https://cloud.githubusercontent.com/assets/2053024/21016116/bff85e98-bd64-11e6-945b-00e0de6129ca.png)

So you should not be able to do so. 
If 1.8 allowed to do it, well... you are kinda in trouble. That is the subnet KUKA uses for the communication with the RTOS. From what you write, once the cabinet reboot it gets stuck at some point in a loop, trying to communicate with the robot.
That means that you won't be able to install another project that fixes the issue.

I had a similar problem some time ago, but I directly messed with the RTOS interface in the cabinet, I was testing something. The result was basically identical and I solved just walking some offices and getting a brand new SSD for my cabinet with everything freshly installed (that is why I dared to try, I had/have this opportunity).

It **MIGHT** be that playing around with the internal KRC folder on the cabinet one **COULD** fix this, in my case it was even worse so I couldn't. But I cannot suggest you to do so.

Final suggestion (if everything I said fits your problem): contact KUKA for support. If you are lucky you could send them your SDD and get a new one (if you are in Germany it should be easy). But as you said, they state the issue in the documentation (and at least from 1.9 they try to prevent it), so they will not get any blame.

In any case, I hope you can solve this quickly. If you need more info let me know!

NOTE: this issues is not due to any modification that is needed to use iiwa_stack, it is just a misconfiguration to a Sunrise Project, that could happen to any project.

NOTE 2: mind that [1.8 does not support the Connectivity package and therefore you cannot use iiwa_stack.](https://github.com/SalvoVirga/iiwa_stack/wiki/FAQ#faqs-and-troubleshooting) You should rather ask for 1.9 with Connectivity to KUKA.
