### ISSUE TITLE
question: using NtpTimeProvider.startPeriodicUpdates(..) instead of polling in ROSBaseApplication.run()

### ISSUE THREAD

**Issue by gavanderhoorn** [SalvoVirga/iiwa_stack#41]
As per subject really.

I was wondering why `ROSBaseApplication.run()` invokes `NtpTimeProvider.updateTime()` instead of configuring the `NtpTimeProvider` instance to manage its own periodic updates using `NtpTimeProvider.startPeriodicUpdates(..)`.

Are the periodic updates too slow / inaccurate for the driver? It would seem to make it possible to do away with the decimation counters and make the while-loop tighter.

**Comment by marcoesposito1988** [comment]
Very good observation! We should see how nice it plays with the threading in the Sunrise JVM. Worth to try!


Marco Esposito
Research Assistant

Computer Aided Medical Procedures (CAMP)
Technische Universit?t M?nchen
Institut fuer Informatik I16
Boltzmannstr. 3<x-apple-data-detectors://4/0>
85748 Garching<x-apple-data-detectors://4/0> b. Muenchen, Germany
campar.in.tum.de<http://campar.in.tum.de/>

E-Mail: marco.esposito@tum.de<mailto:marco.esposito@tum.de>
Phone: +49 89 289 19403<tel:+49%2089%20289%2019403>

Am 08.12.2016 um 16:06 schrieb G.A. vd. Hoorn <notifications@github.com<mailto:notifications@github.com>>:


As per subject really.

I was wondering why ROSBaseApplication.run() invokes NtpTimeProvider.updateTime() instead of configuring the NtpTimeProvider instance to manage its own periodic updates using NtpTimeProvider.startPeriodicUpdates(..).

Are the periodic updates too slow / inaccurate for the driver? It would seem to make it possible to do away with the decimation counters and make the while-loop tighter.

-

**Comment by gavanderhoorn** [comment]
I've tested it with `ROSMonitor` and that seemed fine. Will have to test it with actual motions, but I see no real difference between polling in the while and letting `*Executor` do it for us (other than a few extra context switches now and then): it basically calls the same code.

**Comment by SalvoVirga** [comment]
Fixed, thanks for pointing that out!
